#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#

# Directories.
export INCDIR = $(CURDIR)/include
export SRCDIR = $(CURDIR)/src

# Executable file.
export EXEC = is

# Builds for Intel x86.
x86:
	cd $(SRCDIR) && $(MAKE) x86

# Builds for MPPA-256.
mppa256:
	cd $(SRCDIR) && $(MAKE) mppa256

# Cleans compilation files.
clean:
	cd $(SRCDIR) && $(MAKE) clean
