#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#

# Builds all kernels.
all: fn

# Builds FN kernel.
fn:
	cd FN && $(MAKE) all



# Cleans compilation files.
clean:
	cd FN && $(MAKE) clean
