#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#

# Directories. 
export INCDIR  = $(CURDIR)/include
export SRCDIR  = $(CURDIR)/src
export MPPADIR = /usr/local/k1tools

# Toolchain configuration.
export CFLAGS = 

# Builds everything.
all: 
	mkdir -p bin
	cd $(SRCDIR) && $(MAKE) all

# Cleans compilation files.
clean:
	cd $(SRCDIR) && $(MAKE) clean
