#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#
# Builds CAP Benchmark suite for MPPA-256 architecture.
#

# Builds kernel usync async.
all:
	cd async && $(MAKE) all
	
# Cleans compilation files.
clean:
	cd async && $(MAKE) clean
